### ISSUE TITLE
Built-in RPG Series compatibility (Suggestion)

### ISSUE THREAD

**Issue by Jacob1101** [nvb-uy/Tierify#10]
This would be awesome as it was the only reason I was keeping myself from using TieredZ, it had tiny inconsistencies such as the netherite heavy crossbow only costing flint to reforge (way too overpowered). This mod, on the other hand, seems like it was made for Prominence, which includes the RPG Series so it would be nice to have that compatibility built-in. Besides, I'm not sure how to make a datapack that allows the modded equipment to be reforged :(

**Comment by nvb-uy** [comment]
It already has RPG Series support built-in. If you want to customize it further, make a datapack.
