### ISSUE TITLE
Mod Doesn't Work on 1.21.1

### ISSUE THREAD

**Issue by LordOfTheWeebs** [nvb-uy/Tierify#12]
I attempted to run the mod on my 1.21.1 pack, and it crashed. I thought it might have been Patchouli because that kept coming up in the crash log, but I tested it on a clean instance and it refuses to work.

The mod also requires Cloth Config API, according to the Fabric Loader's incompatible mods pop-up, likely because LibZ seems to be embedded.

I attempted using versions 0.16.5, 0.16.6, and 0.16.7 of the Fabric Loader, all with the same results.

[pre-clothconfig-latest.log](https://github.com/user-attachments/files/17347282/pre-clothconfig-latest.log)
[latest.log](https://github.com/user-attachments/files/17347283/latest.log)

**Comment by nvb-uy** [comment]
Yes, this mod is not updated to 1.21.

**Comment by LordOfTheWeebs** [comment]
If it's not updated to 1.21, then please don't mark it on Modrinth as compatible with 1.21
![Screenshot_20241014_200217](https://github.com/user-attachments/assets/f7fe43cb-a58c-4595-b055-b07881009719)
![Screenshot_20241014_200219](https://github.com/user-attachments/assets/77627c1b-d181-4225-90a2-9a00fc432fcf)
