### ISSUE TITLE
Allow choosing which negative attributes are permitted.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [nvb-uy/Tierify#17]
Paraphrasing a request from @JaredRichardWilliam:

> I don't want maximum health reductions to exist for any items, because reforging modded items can be too time-consuming when the drawbacks (like the aforementioned) are so significant.

**Comment by nvb-uy** [comment]
Just make a datapack and override each values. The mod is very customizable.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nvb-uy/Tierify/issues/17#issuecomment-2425181366

@nvb-uy, I'll try.

**Comment by NiFoox** [comment]
@RokeJulianLockhart Hello! Were you able to do it? could you help me with that?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nvb-uy/Tierify/issues/17#issuecomment-2765162517

@NiFoox, no. However, there is extensive documentation on datapack overrrides. What's difficult is mostly a matter of time, since the datapack author must ensure that their modifications keep pace with updates to the mod pack.
