### ISSUE TITLE
Material from Tech Reborn - reforge not possible

### ISSUE THREAD

**Issue by lukaspupkalipinski** [nvb-uy/Tierify#19]
Materials from tech reborn are bugy. A Reforge is not possible. See Picture

![image](https://github.com/user-attachments/assets/22b522e4-e68e-4207-8f2b-b6be6dd9c9cd)

Repair works fine:
![image](https://github.com/user-attachments/assets/53439e69-93e2-43d2-a801-9d717328b109)

**Comment by lukaspupkalipinski** [comment]
After some analysing, found the issue in the mod (Industrial-Revolution):
https://github.com/GabrielOlvH/Industrial-Revolution/issues/610

**Comment by nvb-uy** [comment]
Make a datapack to fix this manually. You can check the example compat for the mutant monsters items, just do the same but with the specific materials you need. This is a side effect of unifying ores.

**Comment by lukaspupkalipinski** [comment]
Attached is the datapack for the next guy.
[indrev-fix.zip](https://github.com/user-attachments/files/17588616/indrev-fix.zip)
