### ISSUE TITLE
the forge gear doesn't work

### ISSUE THREAD

**Issue by qwerty08wewg** [nvb-uy/Tierify#3]
I'll explain, I put the new iron helmet in the center then the iron ingot on the left but on the right the amethyst splinter won't let me put it.
![Immagine 2024-06-15 151206](https://github.com/nvb-uy/Tierify/assets/143532850/34946c1f-16d5-477c-90d9-caf9c8ebabbf)

**Comment by nvb-uy** [comment]
The mod does not use amethyst as a reforge material, please read the mod page for more info

**Comment by qwerty08wewg** [comment]
What material does he use?
