### ISSUE TITLE
Mod causing issues with "Show Me What You Got" Mod

### ISSUE THREAD

**Issue by C0ffeeGoblin** [nvb-uy/Tierify#8]
The tags for the tooltips of the items contain illegal characters which kick you out of the game.

https://www.curseforge.com/minecraft/mc-mods/show-me-what-you-got

**Comment by iyanyani** [comment]
Bumping this issue - players from our server are also encountering issues getting kicked due to illegal characters when linking items that have colored rarity from Tierify.

**Comment by nvb-uy** [comment]
This has to be fixed from Show me what you got's side. There's already a PR to fix it but hasn't been approved.
